# Generated by Django 2.1.5 on 2019-02-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommender_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=40)),
                ('first_configuration', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('angry', 1), ('joyful', 2), ('sad', 3)], max_length=20)),
                ('companionship', models.CharField(choices=[('withFriends', 1), ('alone', 2)], max_length=20)),
                ('rating', models.IntegerField(default=3)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommender_webapp.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Utente')),
            ],
        ),
    ]
